apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: memcached-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.peteryxu.com
      version: v1alpha1
  description: My First Operator
  displayName: Peter's Memcache Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - memcache
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maintainers:
  - email: peteryxu@us.ibm.com
    name: peter
  maturity: alpha
  provider:
    name: peteryxu.com
    url: www.peteryxu.com
  version: 0.0.0
